if(EXISTS "/home/chenchao/code/cplusplus/chatroom/tests/integration_tests[1]_tests.cmake")
  include("/home/chenchao/code/cplusplus/chatroom/tests/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
