add_test([=[IntegrationTest.ChatFlow]=]  /home/chenchao/code/cplusplus/chatroom/tests/integration_tests [==[--gtest_filter=IntegrationTest.ChatFlow]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IntegrationTest.ChatFlow]=]  PROPERTIES WORKING_DIRECTORY /home/chenchao/code/cplusplus/chatroom/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IntegrationTest.PersistenceTest]=]  /home/chenchao/code/cplusplus/chatroom/tests/integration_tests [==[--gtest_filter=IntegrationTest.PersistenceTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IntegrationTest.PersistenceTest]=]  PROPERTIES WORKING_DIRECTORY /home/chenchao/code/cplusplus/chatroom/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IntegrationTest.ConcurrencyTest]=]  /home/chenchao/code/cplusplus/chatroom/tests/integration_tests [==[--gtest_filter=IntegrationTest.ConcurrencyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IntegrationTest.ConcurrencyTest]=]  PROPERTIES WORKING_DIRECTORY /home/chenchao/code/cplusplus/chatroom/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IntegrationTest.SecurityTest]=]  /home/chenchao/code/cplusplus/chatroom/tests/integration_tests [==[--gtest_filter=IntegrationTest.SecurityTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IntegrationTest.SecurityTest]=]  PROPERTIES WORKING_DIRECTORY /home/chenchao/code/cplusplus/chatroom/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[IntegrationTest.PrometheusMetrics]=]  /home/chenchao/code/cplusplus/chatroom/tests/integration_tests [==[--gtest_filter=IntegrationTest.PrometheusMetrics]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[IntegrationTest.PrometheusMetrics]=]  PROPERTIES WORKING_DIRECTORY /home/chenchao/code/cplusplus/chatroom/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  integration_tests_TESTS IntegrationTest.ChatFlow IntegrationTest.PersistenceTest IntegrationTest.ConcurrencyTest IntegrationTest.SecurityTest IntegrationTest.PrometheusMetrics)
